"""
Pydantic models for plan/jobs schema
"""
from typing import List, Dict, Any, Optional, Literal
from pydantic import BaseModel, Field
from enum import Enum


class JobType(str, Enum):
    """Types of jobs the system can execute"""
    EXTRACT_AUDIO = "extract_audio"
    TRANSCRIBE = "transcribe"
    ALIGN_WORDS = "align_words"
    GENERATE_CAPTIONS = "generate_captions"
    RENDER_VIDEO = "render_video"
    RENDER_SUBTITLES = "render_subtitles"
    SILENCE_CUTTER = "silence_cutter"
    STOCK_FOOTAGE = "stock_footage"
    APPLY_TRANSITIONS = "apply_transitions"


class CaptionStyle(BaseModel):
    """Caption styling configuration"""
    font: str = Field(default="Arial Bold", description="Font family")
    font_size: int = Field(default=48, description="Font size in pixels")
    primary_color: str = Field(default="FFFFFF", description="Text color (ASS hex)")
    outline_color: str = Field(default="000000", description="Text outline color")
    outline_width: int = Field(default=3, description="Outline width")
    position: Literal["bottom", "middle", "top"] = Field(default="bottom", description="Caption position")
    bold: bool = Field(default=True, description="Use bold text")
    italic: bool = Field(default=False, description="Use italic text")
    shadow: int = Field(default=2, description="Shadow depth")


class Job(BaseModel):
    """A single job in the execution plan"""
    job_id: str = Field(description="Unique identifier for this job")
    job_type: JobType = Field(description="Type of job to execute")
    inputs: Dict[str, Any] = Field(default_factory=dict, description="Input parameters for the job")
    outputs: Dict[str, str] = Field(default_factory=dict, description="Expected output artifacts")
    depends_on: List[str] = Field(default_factory=list, description="Job IDs this job depends on")


class ExecutionPlan(BaseModel):
    """Complete execution plan generated by the LLM planner"""
    plan_id: str = Field(description="Unique identifier for this plan")
    intent: str = Field(description="User's original intent/prompt")
    jobs: List[Job] = Field(description="Ordered list of jobs to execute")
    estimated_duration: Optional[int] = Field(None, description="Estimated execution time in seconds")
    

class TranscriptionResult(BaseModel):
    """Result from transcription job"""
    text: str = Field(description="Full transcribed text")
    language: str = Field(description="Detected language code")
    segments: List[Dict[str, Any]] = Field(description="Transcript segments with timestamps")


class AlignmentResult(BaseModel):
    """Result from word alignment job"""
    words: List[Dict[str, Any]] = Field(description="Words with precise start/end timestamps")
    

class CaptionLine(BaseModel):
    """A single caption line with word-level timing"""
    line_id: int
    text: str
    start_time: float
    end_time: float
    words: List[Dict[str, float]] = Field(description="Individual words with their timestamps")


class PlannerRequest(BaseModel):
    """Request to the LLM planner"""
    user_prompt: str = Field(description="User's editing request")
    input_video_path: Optional[str] = Field(None, description="Path to input video")
    available_tools: List[str] = Field(default_factory=list, description="Available tools")
    config: Dict[str, Any] = Field(default_factory=dict, description="System configuration")


class PlannerResponse(BaseModel):
    """Response from the LLM planner"""
    success: bool
    plan: Optional[ExecutionPlan] = None
    missing_inputs: List[str] = Field(default_factory=list, description="Required inputs not provided")
    validation_errors: List[str] = Field(default_factory=list, description="Validation errors")
    message: str = Field(default="", description="Human-readable message")
